title: Math Flash Cards
description: Interactive math flash cards
baseurl: "/Math_Flashcards"
url: "https://kemckai.github.io"
markdown: kramdown
plugins:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
collections:
  flashcards:
    output: false
